"""
Pick a random record from a processed sft_reason jsonl ({prompt,response,answer})
and run CONDITIONAL generation on it via run_sample_cond.py: the prompt is pinned
as the prefix and the model fills the rest (the response). The ground-truth answer
and gold response are printed for comparison.

This mirrors the SFT conditional setup: prefix = prompt (ends with
"Assistant: <think>"), suffix = "" (nothing pinned at the tail), so every
non-prompt position is generated by the model.

Usage
-----
    python sample_one_reason.py \
        --model_path exp_local/sft_reason/<date>/<time> \
        --data data/sft_gpt-oss-120b_filtered_trunc_val.jsonl \
        --steps 256

    # reproducible pick / specific row
    python sample_one_reason.py ... --seed 0
    python sample_one_reason.py ... --index 12
"""

import argparse
import json
import random
import subprocess
import sys


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--data", required=True,
                   help="processed {prompt,response,answer} jsonl")
    p.add_argument("--model_path", required=True,
                   help="trained SEDD run dir (exp_local/...) or a HF model id")
    p.add_argument("--steps", type=int, default=256)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--seed", type=int, default=None,
                   help="seed the random record pick (omit = nondeterministic)")
    p.add_argument("--index", type=int, default=None,
                   help="pick this line index instead of a random one")
    args = p.parse_args()

    with open(args.data, "r", encoding="utf-8") as f:
        records = [json.loads(line) for line in f if line.strip()]
    if not records:
        sys.exit(f"no records in {args.data}")

    if args.index is not None:
        idx = args.index % len(records)
    else:
        if args.seed is not None:
            random.seed(args.seed)
        idx = random.randrange(len(records))

    rec = records[idx]
    prompt = rec["prompt"]
    gold = rec.get("response", "")
    answer = rec.get("answer", "")

    bar = "=" * 92
    print(bar)
    print(f"[picked record #{idx} / {len(records)} from {args.data}]")
    print("\n---- PROMPT (pinned as prefix) ----")
    print(prompt)
    print("\n---- GROUND-TRUTH ANSWER ----")
    print(answer)
    print("\n---- GOLD RESPONSE ----")
    print(gold)
    print(bar)
    print(">> running run_sample_cond.py (model fills the response) ...\n", flush=True)

    cmd = [
        sys.executable, "run_sample_cond.py",
        "--model_path", args.model_path,
        "--prefix", prompt,
        "--suffix", "",                 # pin nothing at the tail -> free response
        "--steps", str(args.steps),
        "--batch_size", str(args.batch_size),
    ]
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
